export const LOCALE_EN = "en";
export const LOCALE_ID = "id";
export const PREFIX_PATH_ICONS_HEADER = "../../";
export const MIN_WIDTH_NAVBAR = 1400;
export const EVENT_LISTENER_RESIZE = "resize";

// Firebase key Remote Configs
export const RC_KEY_SOCIAL_MEDIA_HEADER = "socialMediaHeader"
export const RC_KEY_NAVIGATION_BAR = "navigationBar"
export const RC_KEY_SLIDER_BANNER = "sliderBanner"
export const RC_KEY_POPULAR_DESTINATION = "popularDestination"
export const RC_KEY_RECOMMENDED_PACKAGE = "recommendedPackage"
export const RC_KEY_TOUR_TYPE = "tourType"
export const RC_KEY_ASSOCIATES = "associates"
export const RC_KEY_GALLERY_TRIP = "galleryTrip"
export const RC_KEY_TOUR_PACKAGES = "tourPackages"
export const RC_KEY_DETAIL_PACKAGES = "detailPackages"
export const RC_KEY_MICE = "miceCards"
export const RC_KEY_PROMO_MICE_MAIN_PAGE = "promoMiceMainPageCard"
export const RC_KEY_FAQ = "faq"